### ISSUE TITLE
Api key not loaded properly from .env file

### ISSUE THREAD

**Issue by utkrist** [karser/KarserRecaptcha3Bundle#16]
I am trying to integrate captcha in symfony 4 form.
Steps taken:
1. composer require karser/karser-recaptcha3-bundle
2. Register the bundle
   Register bundle into config/bundles.php:
```
return [
    //...
    Karser\Recaptcha3Bundle\KarserRecaptcha3Bundle::class => ['all' => true],
];
```
3. Add configuration files
  ```
  # config/packages/karser_recaptcha3.yaml (or app/config/config.yml if using Symfony3)
karser_recaptcha3:
    site_key: '%env(RECAPTCHA3_KEY)%'
    secret_key: '%env(RECAPTCHA3_SECRET)%'
    score_threshold: 0.5
```
4. Add site key to .env file
```
###> karser/recaptcha3-bundle ###
RECAPTCHA3_KEY=actual_site_key
RECAPTCHA3_SECRET=actual_secret
###< karser/recaptcha3-bundle ###
```
5. Finally added the form type to the form builder

```
<?php

use Karser\Recaptcha3Bundle\Form\Recaptcha3Type;
use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3;


class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('captcha', Recaptcha3Type::class, [
            'constraints' => new Recaptcha3(),
            'action_name' => 'homepage',
        ]);
        //$builder->add(...);
    }
}
```

Despite all this I am getting following error on my developer tools console:

```
`Uncaught (in promise) Error: Invalid site key or not loaded in api.js: my_site_key
`
```
